### ISSUE TITLE
Reference figures for comparison

### ISSUE THREAD

**Issue by amuetste** [vmware-labs/hci-benchmark-appliance#3]
### Is your feature request related to a problem? Please describe.

After running HCIBench, I'm looking for reference figures to be able to interpret the results. Right now, I do not know if what I see is good or bad, expected or unexpected. 

### Describe the solution you'd like

Would it be possible to add reference figures to the results? It would give you a ballpark about the numbers you see. 

### Describe alternatives you've considered

Alternative is to run it on another vSAN environment to see what that does compared to the initial tested environment. The thing is, a lot of customers do not have 2 or more environments to test. 

### Additional context

I'm talking vSAN specifically but generally it can be for all.

**Comment by cwei44** [comment]
the storage performance could be vary depending on the workloads, h/w, s/w version, data svc on/off, especially for vSAN, it there was a figure telling what's expected performance of vSAN then it would be misleading.

there are some 3rd party has published perf numbers of vSAN using HCIBench:
https://www.storagereview.com/review/maximizing-vsan-8-esa-potential-with-western-digital-ultrastar-dc-sn6555-nvme-ssds
https://community.intel.com/t5/forums/recentpostspage/post-type/message/user-id/186642

also here are few resource talking about storage performance:
https://www.snia.org/sites/default/education/tutorials/2008/spring/storage/Lucchesi-R_Storage_Performance_101.pdf

i guess a more important questions is, whats your workload, whats your goal of running perf test, whats your iops/tput/latency requirement? those questions are more important to address before executing the tests.
