### ISSUE TITLE
PDF Result file generation

### ISSUE THREAD

**Issue by carloshb0** [vmware-labs/hci-benchmark-appliance#6]
### Describe the bug

Hello.
I can get the pdf results file generated after executing an easy-run over a vSAN (specifically the 8K and the 256K easy-runs). Is there a way I can do it manually?
Thanks!

### Reproduction steps

1.Execute the 8K or the 256K easy run over a 22-nodes stretched clúster.
2.
3.
...

### Expected behavior

I would expect the generation of the pdf results file.

### Additional context

The pdf result file for the two of the 4K easy-run where successfully generated.

**Comment by cwei44** [comment]
could you send me the logs in /opt/automation/logs to hcibench@broadcom.com?

**Comment by cwei44** [comment]
as we are removing vsan observer, you can try to use this file:https://github.com/vmware-labs/hci-benchmark-appliance/blob/main/HCIBench/automation/lib/generate_report.rb to replace /opt/automation/lib/generate_report.rb and try:

1. cd /opt/automation/lib
2. ruby generate_report.rb /opt/output/results/TEST-NAME/TEST-CASE-NAME

**Comment by carloshb0** [comment]
> could you send me the logs in /opt/automation/logs to [hcibench@broadcom.com](mailto:hcibench@broadcom.com)?

Hi, cwei44.
Already did (send the logs to that email address) as a colleague of yours (?) is helping with the case. Sorry for the duplicates.
Anyway, I will test your suggestion of replacing the generate_report.rb file.
Regards.

**Comment by carloshb0** [comment]
Hello.
After trying again replacing the generate_report.rb file with the one you suggested, the command DID create the .pdf file! :-)
I will test again with the other easy_run that failed and let you know.
Thanks!

**Comment by carloshb0** [comment]
Hi.

Just to let you know that the generation of the second .pdf file worked too :-)

root@photon-HCIBench [ /opt/automation/lib ]# ruby generate_report.rb /opt/output/results/easy-run-1712822857/fio-8vmdk-100ws-256k-0rdpct-0randompct-1threads-50compress-50dedupe-1712826083
2024-04-19 10:52:38 +0000: Get the start time and stop time of tests, and scale them correctly
2024-04-19 10:52:38 +0000: Download the screenshots to the images/fio or images/vdbench directories
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4917  100  4917    0     0   3096      0  0:00:01  0:00:01 --:--:--  3094
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5117  100  5117    0     0   3271      0  0:00:01  0:00:01 --:--:--  3271
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3663  100  3663    0     0   2322      0  0:00:01  0:00:01 --:--:--  2321
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5745  100  5745    0     0   3692      0  0:00:01  0:00:01 --:--:--  3692
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4555  100  4555    0     0   2921      0  0:00:01  0:00:01 --:--:--  2919
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6128  100  6128    0     0   3974      0  0:00:01  0:00:01 --:--:--  3971
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9032  100  9032    0     0   5782      0  0:00:01  0:00:01 --:--:--  5782
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5659  100  5659    0     0   3634      0  0:00:01  0:00:01 --:--:--  3632
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6377  100  6377    0     0   4038      0  0:00:01  0:00:01 --:--:--  4038
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7477  100  7477    0     0   4783      0  0:00:01  0:00:01 --:--:--  4780
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 87394  100 87394    0     0  51681      0  0:00:01  0:00:01 --:--:-- 51681
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82634  100 82634    0     0  49245      0  0:00:01  0:00:01 --:--:-- 49245
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1344  100  1344    0     0     21      0  0:01:04  0:01:02  0:00:02   357
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64947  100 64947    0     0  38612      0  0:00:01  0:00:01 --:--:-- 38612
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21705  100 21705    0     0  13036      0  0:00:01  0:00:01 --:--:-- 13028
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78852  100 78852    0     0  47301      0  0:00:01  0:00:01 --:--:-- 47301
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19048  100 19048    0     0  11405      0  0:00:01  0:00:01 --:--:-- 11399
2024-04-19 10:54:06 +0000: Read the templates
2024-04-19 10:54:06 +0000: Replate the hcitags in the template with the actual data
2024-04-19 10:54:06 +0000: Handle the special chars in the url
govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
Error: option '--path' needs a parameter.
Try --help for help.
2024-04-19 10:54:17 +0000: Read the result content and replace the hcitag in the html template
2024-04-19 10:54:17 +0000: Generate html file from the template
2024-04-19 10:54:17 +0000: Generate the pdf file using weasyprint
ERROR: Failed to load image at "file:///opt/automation/lib/report/images/fio/8.png" (Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.)
2024-04-19 10:54:17 +0000: Clean the contents in the template folder
root@photon-HCIBench [ /opt/automation/lib ]#



Thanks!!

**Comment by cwei44** [comment]
closing issue for now
